name: "CI: autotools: gcc 9"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - uses: docker://ubuntu:19.10
    - name: Build
      run: |
        sudo apt update
        sudo apt install mm-common g++-9
        export CXX=g++-9
        mkdir build
        cd build
        ../autogen.sh --enable-warnings=fatal
        make
    - name: Test
      run: |
        cd build
        make check
    - name: Distcheck
      run: |
        cd build
        make distcheck
