name: "CI: autotools: gcc 7"

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build
      run: |
        sudo apt update
        sudo apt install mm-common g++-7
        export CXX=g++-7
        ./autogen.sh
        ./configure
        make
    - name: Test
      run: make check
    - name: Distcheck
      run: make distcheck
