name: "CI: cmake"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build
      run: |
        cmake .
        make
    - name: Test
      run: make test
